name: Deploy Dashboards to GitHub Pages

on:
  push:
    branches: [gh-pages]
    paths:
      - 'apps/**'
      - '.github/workflows/gh-pages.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [dashboard-project-management-1] # Add more as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build app - ${{ matrix.app }}
        run: npm run build --workspace=apps/${{ matrix.app }}

      - name: Deploy ${{ matrix.app }} to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/${{ matrix.app }}/dist
          destination_dir: ${{ matrix.app }}
